[[extensions]]
name = "DunBuilder Flow trigger"
handle = "dunbuilder-flow-trigger"
type = "flow_trigger"

description = "Dun Builder description"

[settings]



  [[settings.fields]]
  type = "single_line_text_field"
  key = "Wall width"


  [[settings.fields]]
  type = "single_line_text_field"
  key = "Wall height"



  [[settings.fields]]
  type = "single_line_text_field"
  key = "Dun width"


  [[settings.fields]]
  type = "single_line_text_field"
  key = "Dun height"

    [[settings.fields]]
    type = "single_line_text_field"
    key = "Show measurement"

      [[settings.fields]]
        type = "single_line_text_field"
        key = "Form type"

     [[settings.fields]]
    type = "single_line_text_field"
  key = "Shape"

       [[settings.fields]]
      type = "single_line_text_field"
    key = "Vertical density"

         [[settings.fields]]
        type = "single_line_text_field"
      key = "Horizontal Velocity"

           [[settings.fields]]
          type = "single_line_text_field"
        key = "Image"

          [[settings.fields]]
                  type = "single_line_text_field"
                key = "Email"
