# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d810f4ccb33f4ae566f9bae9201a86e"
name = "Dun-wall-builder (Live)"
handle = "dun-wall-builder-live"
application_url = "https://phpstack-362288-4901431.cloudwaysapps.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "tlx-new-brand.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://phpstack-362288-4901431.cloudwaysapps.com/auth/callback",
  "https://phpstack-362288-4901431.cloudwaysapps.com/auth/shopify/callback",
  "https://phpstack-362288-4901431.cloudwaysapps.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
